concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "http://gitlab"
  id = 1
  token = "G1T8xJZrM8Ki7yWn2BzF"
  token_obtained_at = 2025-11-27T01:46:13Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://gitlab"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "gradle:7.6-jdk8"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    network_mode = "cicd-exercise_gitlab-network"
    dns = ["8.8.8.8", "1.1.1.1"]
    shm_size = 0
    network_mtu = 0
