version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ee:15.0.1-ee.0
    container_name: gitlab
    restart: always
    hostname: gitlab.local
    ports:
      - "8080:80"     # 웹 UI
      - "8443:443"    # HTTPS
      - "2222:22"     # SSH
    volumes:
      - /var/gitlab/config:/etc/gitlab
      - /var/gitlab/logs:/var/log/gitlab
      - /var/gitlab/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /var/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock   # Docker-in-Docker 아님. Host Docker 사용